import { RequestData } from '../interfaces'

export const sampleContentData: RequestData = {
  data:{
    container_type:"main",
    container_items:[
       {
          id:156,
          display_name:"dizi",
          items:[
             {
                id:1244,
                name:"Baghdad Central",
                image:"https://img-puhutv.mncdn.com/media/21-09/28/baghdad-centraltitle_7x10.jpg",
                relaseYear:2000,
                meta:{
                   slug:"baghdad-central-dizi-detay"
                }
             },
             {
                id:1247,
                name:"Our Miracle Years",
                image:"https://img-puhutv.mncdn.com/media/21-09/28/our-miracle-yearstitle_7x10.jpg",
                relaseYear:2001,
                meta:{
                   slug:"our-miracle-years-dizi-detay"
                }
             },
             {
                id:1230,
                name:"Chimerica",
                image:"https://img-puhutv.mncdn.com/media/21-09/15/chimericatitle_7x10.jpg",
                relaseYear:1999,
                meta:{
                   slug:"chimerica-dizi-detay"
                }
             },
             {
                id:1245,
                name:"My Brilliant Friend",
                image:"https://img-puhutv.mncdn.com/media/22-06/27/my-brilliant-friend-poster-1.png",
                relaseYear:2005,
                meta:{
                   slug:"my-brilliant-friend-dizi-detay"
                }
             },
             {
                id:1235,
                name:"Roadkill",
                image:"https://img-puhutv.mncdn.com/media/22-06/27/poster_roadkill.jpg",
                relaseYear:1900,
                meta:{
                   slug:"roadkill-dizi-detay"
                }
             }
          ],
          title_count:"5",
          total_pages:1
       },
       {
          id:111,
          display_name:"belgesel",
          items:[
             {
                id:800,
                name:"Esrarengiz Azerbaycan",
                image:"https://img-puhutv.mncdn.com/media/22-12/19/esrarengiz-azerbaycantitle_7x10.jpg",
                relaseYear:2000,
                meta:{
                   slug:"esrarengiz-azerbaycan-detay"
                }
             },
             {
                id:801,
                name:"Halkın Mutfağı",
                image:"https://img-puhutv.mncdn.com/media/21-01/28/halkin-mutfagititle_7x10.jpg",
                relaseYear:2001,
                meta:{
                   slug:"halkin-mutfagi-detay"
                }
             },
             {
                id:802,
                name:"Adım Adım Sağlık",
                image:"https://img-puhutv.mncdn.com/media/22-11/07/adim-adim-sagliktitle_7x10.jpg",
                relaseYear:1999,
                meta:{
                   slug:"adim-adim-saglik-detay"
                }
             },
             {
                id:803,
                name:"Kırılma Anı",
                image:"https://img-puhutv.mncdn.com/media/20-10/03/ntv_kirilma_anititle_7x10.jpg",
                relaseYear:2020,
                meta:{
                   slug:"kirilma-ani-detay"
                }
             },
             {
                id:804,
                name:"Şampiyonlar Ligi'nde Finale Doğru",
                image:"https://img-puhutv.mncdn.com/media/21-05/26/unutulmaz-finaller_puhutitle_7x10.jpg",
                relaseYear:2021,
                meta:{
                   slug:"sampiyonlar-liginde-finale-dogru-detay"
                }
             }
          ],
          title_count:"5",
          total_pages:1
       },
       {
          id:157,
          display_name:"film",
          items:[
             {
                id:1259,
                name:"Ejderha Gözler",
                relaseYear:2004,
                image:"https://img-puhutv.mncdn.com/media/22-02/03/dragon-eyes-ejderha-gozler-poster.png",
                meta:{
                   slug:"ejderha-gozler-film-detay"
                }
             },
             {
                id:1258,
                name:"Uyumsuz",
                image:"https://img-puhutv.mncdn.com/media/22-02/03/divergent-uyumsuz-poster.png",
                relaseYear:2006,
                meta:{
                   slug:"uyumsuz-film-detay"
                }
             },
             {
                id:1257,
                name:"Yarış",
                relaseYear:2009,
                image:"https://img-puhutv.mncdn.com/media/22-02/03/borning-yaris-poster-1-1643869858.png",
                meta:{
                   slug:"yaris-film-detay"
                }
             },
             {
                id:1255,
                name:"Ölümcül Takip",
                relaseYear:2022,
                image:"https://img-puhutv.mncdn.com/media/22-02/03/blitz-poster.png",
                meta:{
                   slug:"olumcul-takip-film-detay"
                }
             },
             {
                id:1254,
                name:"Benimle Git",
                relaseYear:1999,
                image:"https://img-puhutv.mncdn.com/media/22-02/03/blackway-benimle-git-poster.png",
                meta:{
                   slug:"benimle-git-film-detay"
                }
             }
          ],
          title_count:"5",
          total_pages:1
       }
    ],
    total_pages:1,
    "total_count":10,
    "has_more":false
 }
}
